# Hacktiv8-PTP Python For Data Science // S.4 // Numpy

Numpy Intro 
    How to import NumPy
    Why use NumPy?
    Terminology
    What is an array?
    What are the attributes of an array?
    What’s the difference between a Python list and a NumPy array?
    
         1. NumPy Initialization 
         2. Creating Ndarrays in NumPy
         3. Add, Remove, and Sort
         4. Multi-Dimensional Arrays
         5. ndim , shape and size
         6. Sorting Array
         7. Reshape
         8. Convert 1D to 2D
         9. Indexing and Slicing
         10. Creating Array from Existing Data  
         11. Copying
         12. Basic array Operation
         13. Broadcasting 
         14. More Array Operations
         15. Save Array into file
         16. Latihan Studi Kasus x
         17. Matrices 
               Create Matrices 
               Matrix Aritmetic 
               Dot Product 
               Matrix Indexing 
               Matrix Aggregation 
               Transposing and Reshaping 
               N-Dimensional Array 
               Flatten N-Dimensional Array 
         Working with math Formulas 

## Numpy Introduction

    NumPy (Python Numerik) adalah ekstensi open source dari Python Numerical komputasi. 
    Alat ini dapat digunakan untuk menyimpan dan memproses matriks besar. 
    Numpy jauh lebih efisien daripada struktur nested list Python sendiri. 
    Ini mendukung operasi array dan matriks beberapa dimensi. 
    Selain itu juga menyediakan sejumlah besar perpustakaan matematika untuk operasi array 
    Dan digunakan di hampir setiap bidang sains dan teknik. 
    
    NumPy dari tahun 2005 dan membentuk semacam kode sumber terbuka dan dipelihara 
    dan dikembangkan oleh banyak kolaborator bersama-sama.

    NumPy API digunakan secara luas di Pandas, SciPy, Matplotlib, scikit-learn, scikit-image 
    dan sebagian besar paket ilmu data dan Python ilmiah lainnya.

    Pustaka NumPy berisi array multidimensi dan struktur data matriks (Anda akan menemukan informasi lebih 
    lanjut tentang ini di bagian selanjutnya). Ini menyediakan ndarray, objek array n-dimensi homogen, 
    dengan metode untuk beroperasi secara efisien di atasnya. NumPy dapat digunakan untuk melakukan 
    berbagai macam operasi matematika pada array. Itu menambahkan struktur data yang kuat ke Python 
    yang menjamin perhitungan yang efisien dengan array dan matriks dan itu memasok perpustakaan 
    besar fungsi matematika tingkat tinggi yang beroperasi pada array dan matriks ini.


<img src="https://i.ibb.co/HK3pbdm/numpy-base.webp" align="center">

<br>

sumber : Harris, C.R., Millman, K.J., van der Walt, S.J. et al. Array programming with NumPy. Nature 585, 357–362 (2020). https://doi.org/10.1038/s41586-020-2649-2 


#### Installing NumPy

If you already have Python, you can install NumPy with:

conda install numpy

or

pip install numpy


!pip install numpy 

In [1]:
pip install numpy 

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Note: you may need to restart the kernel to use updated packages.


#### How to import NumPy

Setiap kali Anda ingin menggunakan paket atau pustaka dalam kode Anda, Anda harus membuatnya dapat diakses terlebih dahulu.

Untuk mulai menggunakan NumPy dan semua fungsi yang tersedia di NumPy, Anda harus mengimpornya. Ini dapat dengan mudah dilakukan dengan pernyataan impor ini:

import numpy as np

(Kami mempersingkat "numpy" menjadi "np" untuk menghemat waktu dan juga untuk menjaga standarisasi kode sehingga siapa pun yang bekerja dengan kode Anda dapat dengan mudah memahami dan menjalankannya.)

In [ ]:
import numpy as np 

#### Terminology
   ##### What is an array?
    
       Array adalah struktur data pusat dari library NumPy. Ini adalah kisi nilai dan berisi informasi tentang data mentah, cara menemukan elemen, dan cara menafsirkan elemen. Ini memiliki kisi elemen yang dapat diindeks 
       dengan berbagai cara. Semua elemen memiliki tipe yang sama, disebut sebagai tipe array d (tipe data).
    
    Array dapat diindeks oleh tupel bilangan bulat non-negatif, dengan boolean, oleh array lain, atau dengan bilangan bulat. Rank dari array adalah jumlah dimensi. Bentuk array adalah tupel bilangan bulat yang memberikan ukuran array sepanjang setiap dimensi.

    Salah satu cara kita dapat menginisialisasi array NumPy adalah dari daftar Python bersarang.

    a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

    Kita dapat mengakses elemen dalam array menggunakan tanda kurung siku. Saat Anda mengakses elemen, ingatlah bahwa pengindeksan di NumPy dimulai dari 0. Artinya, jika Anda ingin mengakses elemen pertama dalam array, Anda akan mengakses elemen “0”.

        print(a[0])

    Keluaran:

        [1 2 3 4]

    Informasi lebih lanjut tentang array

    array 1D, array 2D, ndarray, vektor, matriks

    Anda mungkin kadang-kadang mendengar array yang disebut sebagai "ndarray," yang merupakan singkatan dari 
    "array N-dimensi." Array N-dimensi hanyalah sebuah array dengan sejumlah dimensi. Anda mungkin juga 
    mendengar 1-D, atau array satu dimensi, 2-D, atau larik dua dimensi, dan seterusnya. 
    
    
    * Kelas NumPy ndarray digunakan untuk mewakili matriks dan vektor. 
    * Vektor adalah array dengan satu kolom. 
    * sedangkan matriks  mengacu pada array dengan banyak kolom.

#### What are the attributes of an array?

     Array biasanya merupakan wadah berukuran tetap dari item dengan jenis 
     dan ukuran yang sama. Jumlah dimensi dan item dalam array ditentukan oleh bentuknya. 
     Bentuk array adalah tupel bilangan bulat non-negatif yang menentukan 
     ukuran setiap dimensi.

    Di NumPy, dimensi disebut sumbu. Ini berarti jika Anda memiliki array 2D yang terlihat seperti ini:

[[0., 0., 0.],
  [1., 1., 1.]]

    Array Anda memiliki 2 sumbu. Sumbu pertama memiliki panjang 2 dan sumbu kedua memiliki panjang 3.

    Sama seperti objek kontainer Python lainnya, isi array dapat diakses dan dimodifikasi dengan mengindeks atau mengiris array. Array yang berbeda dapat berbagi data yang sama, sehingga perubahan yang dibuat pada satu array mungkin terlihat di array lain.

    Atribut array mencerminkan informasi intrinsik ke array itu sendiri. Jika Anda perlu mendapatkan, atau bahkan mengatur, properti array tanpa membuat array baru, Anda sering dapat mengakses array melalui atributnya.



##### What’s the difference between a Python list and a NumPy array?

       NumPy memberi Anda sejumlah besar opsi terkait numerik yang cepat dan efisien. 
       Meskipun list Python dapat berisi tipe data yang berbeda dalam satu list, 
       semua elemen dalam array NumPy harus tipe data yang sama (Jika int harus integer , 
       jika string maka harus string semua data). 
       Operasi matematika yang dimaksudkan untuk dilakukan pada array 
       tidak akan mungkin jika array tidak homogen.

### NumPy Basic

#### Numpy Initialization

In [2]:
pip install numpy 

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python3.9 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 
np.__version__ 

'1.21.2'

#### Why use NumPy?

    Array NumPy lebih cepat dan lebih ringkas daripada list Python. Sebuah array mengkonsumsi lebih 
    sedikit memori dan jauh lebih nyaman untuk digunakan. NumPy menggunakan lebih sedikit memori 
    untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, 
    yang memungkinkan kode untuk dioptimalkan lebih jauh.
    
    Numpy adalah library aljabar linear untuk python 

Membandingkan kecepatan antara numpy dengan list core python

In [3]:
# code 
b = list(range(10))
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
# code function sum menggunakan list 
# menambahkan list a dan list b dari jumlah range sebagai inputan
# a akan di pangkat 2 dan b akan dipangkatkan dengan 3 
# hasil akhir akan menjumlahkan a dan b 
def python_listsum(n):
    a = b = list(range(n)) # menginisialisasi a dan b dari list range 
    output = []
    for idx in range(len(a)):
        x = a[idx] ** 2 
        y = b[idx] ** 3
        output.append(x+y)
    
    return output


In [5]:
output_listsum = python_listsum(10)
print(output_listsum)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [7]:
def numpy_sum(n):
    x = np.arange(n) ** 2 
    y = np.arange(n) ** 3  
    return x+y 

In [8]:
output = numpy_sum(10)
print(output)

[  0   2  12  36  80 150 252 392 576 810]


In [16]:
# kita bandingkan dengan waktu menggunakan lib datetime 
from datetime import datetime
size = 1000000
awal = datetime.now()
## call func 
output = python_listsum(100)
end = datetime.now() - awal 
print(f"Waktu yang dibutuhkan : {end.microseconds}")
print(f"Data 2 akhir dari list : {output[-2:]}")

Waktu yang dibutuhkan : 122
Data 2 akhir dari list : [950796, 980100]


In [17]:
from datetime import datetime
size = 1000000
awal = datetime.now()
## call func 
output = numpy_sum(100)
end = datetime.now() - awal 
print(f"Waktu yang dibutuhkan : {end.microseconds}")
print(f"Data 2 akhir dari list : {output[-2:]}")

Waktu yang dibutuhkan : 93
Data 2 akhir dari list : [950796 980100]


In [18]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

_____

#### Create An Ndarrays

In [19]:
import numpy as np

listrange = list(range(5))
print(listrange)
print(type(listrange))

[0, 1, 2, 3, 4]
<class 'list'>


In [20]:
nparr = np.array(listrange)
print(nparr)
print(type(nparr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [24]:
print(np.arange(5)) # (start  default = 0  , stop , step default = 1)

print(np.arange(1,9)) # start  = 1 , stop = 9 , step default =1 

print(np.arange(1,15,2)) # start  = 1 , stop = 15 , step = 2 


[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[ 1  3  5  7  9 11 13]


_____

#### Add, Remove, and Sort
- np.append() 
- np.delete()
- np.sort()
  np.sort(a, axis=1, kind=None, order=None)

In [26]:
#code 
nparr  = np.arange(1,11)
print(nparr)
print(type(nparr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [27]:
#code
new_np = np.append(nparr, [12,14])
print(new_np)

[ 1  2  3  4  5  6  7  8  9 10 12 14]


In [28]:
np.delete(new_np, 4)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 12, 14])

In [29]:
np.sort?

Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [31]:
arr_acak = np.array([4,2,1,10,6,8,5,7,3])
arr_sort = np.sort(arr_acak)
print(arr_sort)

[ 1  2  3  4  5  6  7  8 10]


_____

### Multi-Dimensional Arrays
    NumPy array memudahkan kita untuk membuat array multi-dimensi.

<img src="https://i.ibb.co/dDQnK4S/2DArray.png" align="center">


#### ndim , shape and size

In [34]:
#code
multiplelist= [[0,1,2,3], [10,11,12,13]]
print(multiplelist)

np_arr = np.array(multiplelist)
print(f"{np_arr}")
print(f" nidm : {np_arr.ndim}, shape : {np_arr.shape}, size : {np_arr.size}")

[[0, 1, 2, 3], [10, 11, 12, 13]]
[[ 0  1  2  3]
 [10 11 12 13]]
 nidm : 2, shape : (2, 4), size : 8


  ndarray.ndim akan memberi tahu Anda jumlah sumbu, atau dimensi, dari array.

  ndarray.size akan memberi tahu Anda jumlah total elemen array. Ini adalah produk dari elemen bentuk array.

  ndarray.shape akan menampilkan tupel bilangan bulat yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. Jika, misalnya, Anda memiliki array 2D dengan 2 baris dan 4 kolom, bentuk array Anda adalah (2,4).

<img src="https://i.ibb.co/LRLN7ZP/shape.png" align="center">

#### Size
<img src="https://i.ibb.co/KN199JW/size.png" align="center"> 

### Contoh 3 Demensi

In [39]:
#code
np_arr3 = np.array (  [
             [[0,1,2,3],[4,5,6,7]],
             [[8,9,10,11],[12,13,14,15]],
             [[20,21,22,23],[24,25,26,27]]
              ])
print(np_arr3)
print(np_arr3.shape)
print(np_arr3.size)
print(np_arr3.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[20 21 22 23]
  [24 25 26 27]]]
(3, 2, 4)
24
3


_____

    Pada array multi-dimensi kita dapat mengakses nilai elemen berdasarkan indeks dengan pemisah tanda koma [,]. 
    Misalkan kita ingin mendapatkan data pada baris ke-1 dan kolom ke-3 dari array a,
    maka dilakukan perintah a[1, 3].

    Misalkan, kita akan mengganti data pada baris ke-1 dan kolom ke-3 pada array a dengan nilai -1, 
    kita dapat langsung assign nilai baru tersebut pada indeks.

<img src="https://i.ibb.co/LPDSf6N/2dimx.png" align="center"> 

In [40]:
#code
arra_d = [[0,1,2,3], [10,11,12,13]]
np_arr2d = np.array(arra_d)
print(np_arr2d)

[[ 0  1  2  3]
 [10 11 12 13]]


In [42]:
print(np_arr2d[1,3])
np_arr2d[1,3] = -1
print(np_arr2d)

13
[[ 0  1  2  3]
 [10 11 12 -1]]


______

 #### Sorting Array
 
 np.sort?  ## Signature: np.sort(a, axis=-1, kind=None, order=None)

|   kind    |  speed  |    stable |
|:--------|:-------|:--------| 
|'quicksort' |   1    |          no |
|'heapsort'  |   3   |          no |
|'mergesort' |   2   |       yes |
|'timsort'   |   2  |          yes |


#### Sorting

In [49]:
field_mhs  = [('name','S10'), ('ipk',float), ('age',int)]
print(field_mhs)  

[('name', 'S10'), ('ipk', <class 'float'>), ('age', <class 'int'>)]


In [50]:
value_mhs = [('Sule',3.5, 25), ('Azis',3.9, 24), ('Parto',3.2, 30), ('Andre',3.2, 24) ]
print(value_mhs)

[('Sule', 3.5, 25), ('Azis', 3.9, 24), ('Parto', 3.2, 30), ('Andre', 3.2, 24)]


In [51]:
data_mhs = np.array(value_mhs, dtype = field_mhs)
print(data_mhs)

[(b'Sule', 3.5, 25) (b'Azis', 3.9, 24) (b'Parto', 3.2, 30)
 (b'Andre', 3.2, 24)]


In [52]:
data_sortby_name = np.sort(data_mhs, order='name')
print(data_sortby_name)

[(b'Andre', 3.2, 24) (b'Azis', 3.9, 24) (b'Parto', 3.2, 30)
 (b'Sule', 3.5, 25)]


In [53]:
data_sortby_ageipk = np.sort(data_mhs, order=['age','ipk'])
print(data_sortby_ageipk)

[(b'Andre', 3.2, 24) (b'Azis', 3.9, 24) (b'Sule', 3.5, 25)
 (b'Parto', 3.2, 30)]


#### Sorting dengan Structure

______

#### zeroes 

  Sering ada kasus ketika kita ingin NumPy menginisialisasi nilai array untuk kita. NumPy menyediakan metode seperti one(), zeros(), dan lain-lain untuk kasus ini. Kami hanya memberikan mereka jumlah elemen yang kami ingin hasilkan: 

In [54]:
#code 
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

_______

### Reshape

    Menggunakan np.reshape() akan memberikan bentuk baru ke array tanpa mengubah data. 
    Ingatlah bahwa ketika Anda menggunakan metode reshape.  
    -  output dari array memiliki jumlah elemen yang sama dengan array aslinya. 
     12 element :  4x3 , 3x4 , 12 x 1 , 6x2
    
    Dengan np.reshape, Anda dapat menentukan beberapa parameter opsional:

numpy.reshape(a, newshape, order)

    a adalah array yang akan dibentuk kembali.
    newshape : int atau tuple dari ints
    newshape : bentuk baru yang Anda inginkan. 
               Anda dapat menentukan bilangan bulat atau tupel bilangan bulat. 
               Jika Anda menentukan bilangan bulat, hasilnya akan berupa array dengan panjang tersebut. 
               Bentuknya harus sesuai dengan bentuk aslinya.
    order    : 'C' berarti membaca/menulis elemen menggunakan urutan indeks seperti C,
               'F' berarti membaca/menulis elemen menggunakan urutan indeks seperti Fortran, 
               'A' berarti membaca/menulis elemen dalam seperti Fortran urutan indeks 
                jika a adalah Fortran bersebelahan dalam memori, urutan seperti C sebaliknya. 
                (Ini adalah parameter opsional dan tidak perlu ditentukan.)
                Default = C 



In [59]:
#Code
datax  = np.arange(6)
print(datax)
print(datax.shape)

[0 1 2 3 4 5]
(6,)


In [60]:
reshape_a = datax.reshape(2,3)
print(reshape_a)
print(reshape_a.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [61]:
reshape_b = datax.reshape(3,2)
print(reshape_b)
print(reshape_b.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [62]:
reshape_b = datax.reshape(3,3)


ValueError: cannot reshape array of size 6 into shape (3,3)

In [63]:
datay = np.arange(5)
print(datay)
res_y = datay.reshape(2,2)
print(res_y)

[0 1 2 3 4]


ValueError: cannot reshape array of size 5 into shape (2,2)

_______

#### Convert 1D to 2D
    np.newaxis
    np.expand_dims
    
    Anda dapat menggunakan np.newaxis dan np.expand_dims untuk meningkatkan dimensi array yang ada.

     Menggunakan np.newaxis akan meningkatkan dimensi array Anda satu dimensi saat digunakan sekali. 
     Artinya array 1D akan menjadi array 2D, 
     Array 2D akan menjadi Array 3D, dan seterusnya.

     Misalnya, jika Anda mulai dengan array ini:

In [64]:
#Code
datad = np.arange(2,8) 
print(datad)
print(datad.shape)
print(datad.ndim)

[2 3 4 5 6 7]
(6,)
1


In [65]:
new_datad = datad[np.newaxis]
print(new_datad)
print(new_datad.shape)
print(new_datad.ndim)

[[2 3 4 5 6 7]]
(1, 6)
2


In [66]:
vector = datad[np.newaxis, : ]
print(vector)
print(vector.shape)

[[2 3 4 5 6 7]]
(1, 6)


In [67]:
vector_column = datad[ : ,np.newaxis]
print(vector_column)
print(vector_column.shape)
print(vector_column.ndim)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(6, 1)
2


________

#### Indexing and Slicing
Kalian dapat mengindeks dan slice array NumPy dengan cara yang sama seperti kalian slice lists Python.

Array NumPy juga mendukung slice, seperti kalian slice lists Python, dengan menggunakan operator titik dua (yaitu arr[:]) untuk mengiris. Kita juga dapat menggunakan pengindeksan negatif untuk mengiris ke arah belakang.

Kode di bawah ini menunjukkan potongan contoh array NumPy 1-D.

In [68]:
#Code
datanp = np.array([0,1,2,3,4,5,6,7,8,9])
print(datanp)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
print(datanp[1])
print(datanp[-1])

1
9


In [72]:
print(datanp[1:5])


[1 2 3 4]


In [73]:
print(datanp[-2:])


[8 9]


_______

Membuat Subset atau mengiris dari Array dengan menggunakan kondisi tertentu


In [74]:
#Code
list2d = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
np2d = np.array(list2d)
print(np2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
print(np2d[np2d<6]) # mengambil data np 2d yang lebih kecil dari 6 

[0 1 2 3 4 5]


In [76]:
kondisi_lebihdari_7 = (np2d >7)


In [77]:
print(np2d[kondisi_lebihdari_7])

[ 8  9 10 11]


In [79]:
kondisi2 = (np2d > 3) & (np2d <7)

In [80]:
print(np2d[kondisi2])

[4 5 6]


In [81]:
print(np2d[np2d % 2 == 1])

[ 1  3  5  7  9 11]


_____

### Creating Array from Existing Data
    slicing indexing
    np.vstack()
    np.hstack()
    np.hsplit()
    .view()
    .copy()

Anda dapat dengan mudah menggunakan buat array baru dari bagian array yang ada. Katakanlah Anda memiliki array ini:

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Anda dapat membuat array baru dari bagian array Anda kapan saja dengan menentukan di mana Anda ingin mengiris array Anda.

In [82]:
#Code
np_arr1 = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np_arr1[4:9])

[5 6 7 8 9]


In [84]:
np_a2d = np.array([[1,1],[2,2]])
np_b2d = np.array([[3,3],[4,4]])
print(np_a2d)
print(np_b2d)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [85]:
npv = np.vstack((np_a2d, np_b2d))
print(npv)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [86]:
nph = np.hstack((np_a2d, np_b2d))
print(nph)

[[1 1 3 3]
 [2 2 4 4]]


In [87]:
arr_s = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr_s)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [92]:
res_split = np.hsplit(arr_s,5)
print(res_split)
print(type(res_split))

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5,  6],
       [15, 16]]), array([[ 7,  8],
       [17, 18]]), array([[ 9, 10],
       [19, 20]])]
<class 'list'>


______

### Copying 

    Serupa dengan List Python, pada saat membuat referensi ke array NumPy, itu tidak membuat array yang berbeda.
    Oleh karena itu, jika kita mengubah nilai menggunakan variabel referensi, itu juga mengubah array asli. 
    Jika tidak ingin merubah nilai asli menggunakan fungsi copy() 
    Fungsi tidak memiliki argumen yang diperlukan, dan mengembalikan array yang disalin.

    Dalam contoh kode di bawah ini, c adalah referensi ke while d adalah salinannya. Oleh karena itu, perubahan c menyebabkan perubahan yang sama pada a, sedangkan perubahan d tidak mengubah nilai b.

In [93]:
#Code
x = [0,1]
y = [2,4] 
z = x
print(x)
print("##"*10)
z[0] = 10
print(z)

[0, 1]
####################
[10, 1]


In [94]:
newy = y.copy()
newy[0] = 100
print(newy)
print(y)

[100, 4]
[2, 4]


_____

#### Basic array operations
Addition, subtraction, multiplication, division, and more

    Setelah Anda membuat array, Anda dapat mulai bekerja dengannya. Katakanlah, misalnya, Anda telah membuat dua array, satu disebut "data" dan satu lagi disebut "ones".

    Anda dapat menambahkan array bersama dengan tanda plus.

    data + ones

    Anda tentu saja dapat melakukan lebih dari sekadar penambahan.

    data - data yang * data data / data Operasi dasar sederhana dengan NumPy. Jika Anda ingin menemukan jumlah elemen dalam array, Anda akan menggunakan sum(). Ini berfungsi untuk larik 1D, larik 2D, dan larik dalam dimensi yang lebih tinggi.

    data - ones
    data * data
    data / data

    Operasi dasar sederhana dengan NumPy. Jika Anda ingin menemukan jumlah elemen dalam array, Anda akan menggunakan sum(). Ini berfungsi untuk larik 1D, larik 2D, dan larik dalam dimensi yang lebih tinggi.

In [95]:
#Code
np1d = np.array([1,2,3,4,5,6,7,8])
print(np1d.sum())

36


In [97]:
np2da = np.array([[10,20],[30,50]])

print(np2da)
print("#"*10)
print(np2da.sum(axis=0)) # menjumlahkan baris 
print("#"*10)
print(np2da.sum(axis=1)) # menjumlahkan kolom 


[[10 20]
 [30 50]]
##########
[40 70]
##########
[30 80]


_____

### Broadcasting


    Ada kalanya Anda mungkin ingin melakukan operasi antara array dan satu angka (juga disebut operasi 
    antara vektor dan skalar) atau antara array dengan dua ukuran berbeda.

    Misalnya, array Anda (kami akan menyebutnya "data") mungkin berisi informasi tentang jarak dalam mil 
    tetapi Anda ingin mengubah informasi tersebut menjadi kilometer. Anda dapat melakukan operasi ini dengan:
    
    data * 1.6

<img src="https://i.ibb.co/t3Y0GvK/broadcast.png" align="left"> 


    NumPy memahami bahwa perkalian harus terjadi dengan setiap sel. Konsep itu disebut broadcasting.

    Broadcasting adalah mekanisme yang memungkinkan NumPy untuk melakukan operasi pada array dari berbagai bentuk. 
    Dimensi array Anda harus kompatibel, misalnya, ketika dimensi kedua array sama 
    atau ketika salah satunya adalah 1. Jika dimensi tidak kompatibel, Anda akan mendapatkan kesalahan nilai.

   
   

In [98]:
data_b = np.array([1,2])
new_datab = data_b * 1.6 
print(new_datab)

[1.6 3.2]


<img src="https://i.ibb.co/M2s1TqC/e-numpy-broadcasting.png" align="left"> 


In [ ]:
#Code

_____

## Function
Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. Kami menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan kami untuk mengontrol output dari fungsi pseudo-random. Fungsi mengambil satu bilangan bulat sebagai argumen, yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed random yang sama. Perhatikan bagaimana output dari 
fungsi random di setiap proses berikutnya adalah identik ketika ditetapkan random seed yang sama.
Beberapa fungsi utilitas dasar dari modul np.random adalah np.random.seed dan np.random.shuffle. 

Dalam menggunakan fungsi np.random.seed untuk mengatur random seed, yang memungkinkan dilakukan 
untuk mengontrol output dari fungsi pseudo-acak. Fungsi mengambil satu bilangan bulat sebagai argumen, 
yang mewakili random seed.

Kode di bawah ini menggunakan np.random.seed dengan seed acak yang sama. 
Perhatikan bagaimana output dari fungsi random di setiap proses berikutnya adalah identik ketika 
kita menetapkan random seed yang sama.

#### random

In [102]:
#code
print(np.random.randint(30))

16


In [109]:
np.random.seed(1)
print(np.random.randint(30))

5


In [117]:
print(np.random.randint(10,30,10))


[25 25 17 29 20 24 10 11 27 23]


In [120]:
np.random.seed(2)
print(np.random.randint(5,high=20,size=(2,2)))



[[13 18]
 [13 11]]


________

### More Array Operations 
        Maximum, minimum, sum, mean, product, standard deviation, and more

    NumPy juga melakukan fungsi agregasi. Selain min, max, dan sum, 
    Anda dapat dengan mudah menjalankan mean untuk mendapatkan rata-rata, 
    prod untuk mendapatkan hasil perkalian elemen, std untuk mendapatkan standar deviasi, dan banyak lagi.
    
    data.max()
    data.min()
    data.sum()

In [121]:
#Code
print(np1d)

[1 2 3 4 5 6 7 8]


In [124]:
np1d.max()
np1d.sum()

36

In [127]:
print(np2da)
print(np2da.max())
print(np2da.min())
print(np2da.sum())

[[10 20]
 [30 50]]
50
10
110


_______

### save array into file & load file numpy

In [129]:
#Code
data_arr = np.array([[0.12345211,1.12345211,3.12345211,2.12345211],
         [3.12345211,7.12345211,6.12345211,4.12345211],
         [4.12345211,9.12345211,8.12345211,5.12345211]])
print(data_arr)

[[0.12345211 1.12345211 3.12345211 2.12345211]
 [3.12345211 7.12345211 6.12345211 4.12345211]
 [4.12345211 9.12345211 8.12345211 5.12345211]]


In [130]:
np.save("my_numpy_arr.npy",data_arr)

In [131]:
data_arr_new = np.load("my_numpy_arr.npy")
print(data_arr_new)

[[0.12345211 1.12345211 3.12345211 2.12345211]
 [3.12345211 7.12345211 6.12345211 4.12345211]
 [4.12345211 9.12345211 8.12345211 5.12345211]]


________

### Matrices

Anda dapat meneruskan list of list Python untuk membuat matriks untuk mewakilinya di NumPy.

Membuat Matriks
np.array([[1,2],[3,4]])

Kami juga dapat menggunakan metode yang sama yang kami sebutkan di atas (ones(), zeros(), dan random.random()) selama kami memberi mereka tupel yang menjelaskan dimensi matriks yang kami buat

np.ones((3,2))
np.nol((3,2))
np.random.random((3,2))


In [ ]:
#Code

_______

### Matrix Arithmetic
    Kita dapat menjumlahkan dan mengalikan matriks menggunakan operator aritmatika (+ - * / ) 
    Jika kedua matriks tersebut berukuran sama. 
    Numpy menangani sebagai position-wise operations. 
    

In [132]:
#Code
m_data =np.array([[1,2],[4,5]])
print(m_data)

[[1 2]
 [4 5]]


In [134]:
np_one = np.ones([2,2])
print(np_one)

[[1. 1.]
 [1. 1.]]


In [135]:
print(m_data + np_one)

[[2. 3.]
 [5. 6.]]


_________

### Dot Product 
    
    Perbedaan utama yang harus dibuat dengan aritmatika adalah kasus perkalian matriks menggunakan produk titik. NumPy memberikan setiap matriks metode dot() yang dapat kita gunakan untuk melakukan operasi produk dot dengan matriks lain

In [159]:
np.dot?


Docstring:
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
  and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the r

In [136]:
#Code
np.dot(3,4)

12

______

### Matrix Indexing
    Operasi pengindeksan dan pemotongan menjadi lebih berguna saat kita memanipulasi matriks
    
    
   ```np.array([[1, 2], [3, 4], [5, 6]])```

    
<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 


In [139]:
#Code
data_m = np.array([[1, 2], [3, 4], [5, 6]])
print(data_m)
print("*"*10)
print(data_m[0,1]) ## baris ke 0 dan kolom ke 1
print(data_m[1:]) ## baris ke 1 sampai ke 3 (3 tidak include) dan untuk semua kolom
print(data_m[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
**********
2
[[3 4]
 [5 6]]
[1 3]


<img src="https://i.ibb.co/4sS8HGD/Screen-Shot-2021-09-02-at-8-26-34-AM.png" align="left"> 

In [ ]:
#Code

<img src="https://i.ibb.co/MS7b4kK/b-numpy-view.png" align="left"> 


<img src="https://i.ibb.co/rQN75GL/numpy-indexing-arrays-width-1200.jpg" align="left"> 


In [141]:
#Code
vkotak = np.arange(1,17,1)
print(vkotak)

kotak4x4 = vkotak.reshape(4,4)
print(kotak4x4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


<img src="https://i.ibb.co/rQN75GL/numpy-indexing-arrays-width-1200.jpg" align="left"> 


In [142]:
print(kotak4x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [147]:
#Code
print(kotak4x4[1::2, 0::2])
print(kotak4x4[1,2:4])
print(kotak4x4[:,1])
print(kotak4x4[-2:, 2:])

[[ 5  7]
 [13 15]]
[7 8]
[ 2  6 10 14]
[[11 12]
 [15 16]]


____________

### Matrix Aggregation
    Kita dapat menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vector

In [148]:
np2da = np.array([[1, 2],[4,6],[8,10]])

In [149]:
print(np2da)
print(np2da.max())
print(np2da.min())
print(np2da.sum())

[[ 1  2]
 [ 4  6]
 [ 8 10]]
10
1
31


_______

### Transposing and Reshaping¶

Kebutuhan umum ketika berhadapan dengan matriks adalah kebutuhan untuk memutarnya. Ini sering terjadi ketika kita perlu mengambil produk titik dari dua matriks dan perlu menyelaraskan dimensi yang mereka bagi. Array NumPy memiliki properti nyaman yang disebut T untuk mendapatkan transpos matriks.


mentraspose suatu array adalah proses mengubah posisi **element2 vektor baris menjadi vektor kolom demikian pula sebaliknya.* 

Menggunakan numpy , melakukan traspose suatu array dapat dilakukan : 
 dengan cara memangil function **transpose()** atau memanggil properti **T** dari suatu array  

In [151]:
#Code
datat = np.array([[1,2],[3,4],[5,6]])
print(datat)

[[1 2]
 [3 4]
 [5 6]]


In [152]:
print(datat.transpose())

[[1 3 5]
 [2 4 6]]


In [153]:
print(datat.T)

[[1 3 5]
 [2 4 6]]


In [155]:
dataT = np.array([[1,2,3,4,5,6]]).T
print(dataT)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [156]:
print(dataT.reshape(2,3))
print(dataT.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


______

### N-Dimensional Array 
    NumPy dapat melakukan semua yang telah kita sebutkan dalam sejumlah dimensi. Struktur data pusatnya disebut ndarray (N-Dimensional Array) karena suatu alasan.

In [ ]:
#Code

### Flatten N-Dimensional Array

Ada dua cara populer untuk meratakan array: .flatten() dan .ravel(). Perbedaan utama antara keduanya adalah bahwa array baru yang dibuat menggunakan ravel() sebenarnya adalah referensi ke array induk. Ini berarti bahwa setiap perubahan pada array baru akan mempengaruhi array induk juga. Karena ravel tidak membuat salinan, ini hemat memori.

In [157]:
#Code
datat = np.array([[1,2],[3,4],[5,6]])
data_flat = datat.flatten()
print(data_flat)


[1 2 3 4 5 6]


______

### Working with Math Formulas 

    Menerapkan rumus matematika yang bekerja pada array adalah salah satu hal yang membuat NumPy sangat dihormati di komunitas Python ilmiah.

    Misalnya, ini adalah rumus mean square error (rumus utama yang digunakan dalam model pembelajaran mesin terawasi yang menangani regresi):


Misalnya, ini adalah rumus mean square error (rumus utama yang digunakan dalam supervised machine learning model yang menangani regresi):

<br>

<img src="https://i.ibb.co/7tTftxS/Screen-Shot-2021-09-02-at-12-18-44-PM.png" align="left"> 
   


error (1/n) * np.sum(np.square(observed - prediction)) 


_______

Optional

<img src="https://i.ibb.co/WK6XHvh/a-numpy-structure.png" align="left"> 


In [159]:
np_ds = np.arange(12)
print(np_ds)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [160]:
print(np_ds.dtype)
print(np_ds.shape)
print(np_ds.strides)

int64
(12,)
(8,)


In [161]:
np_ds_2d = np_ds.reshape(4,3)
print(np_ds_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [162]:
print(np_ds_2d.dtype)
print(np_ds_2d.shape)
print(np_ds_2d.strides)

int64
(4, 3)
(24, 8)


In [163]:
np_ds_int16 = np_ds_2d.astype('int16')

np_ds_int16.strides 

(6, 2)

<img src="https://i.ibb.co/MS7b4kK/b-numpy-view.png" align="left"> 


<img src="https://i.ibb.co/YN5XSDY/c-numpy-indexing-copy.png" align="left"> 


<img src="https://i.ibb.co/Ybz0vBR/d-numpy-vectorization.png" align="left"> 


<img src="https://i.ibb.co/M2s1TqC/e-numpy-broadcasting.png" align="left"> 


<img src="https://i.ibb.co/FVbnhdc/f-numpy-reduction.png" align="left"> 

<img src="https://i.ibb.co/QbjwCCD/numpy-reduction2.png" align="left"> 


______

## Np read csv 

import csv 

In [164]:
import csv 

In [166]:
data = [] 
filename = 'data/MER_T07_02A.csv'
#....
with open(filename, 'r') as csv_file:
    csv_reader = csv.reader(csv_file,delimiter=',')
    for row in csv_reader: 
        data.append(row)

data = np.array(data)
print(data.shape)
print(data.size)
print(data[-1:,0:1])

np.save(open('datamert.npy', 'wb'),    data)

(8542, 6)
51252
[['ELETPUS']]
